# Generated by Django 5.1.6 on 2025-02-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('scientific_field', models.CharField(max_length=255)),
                ('course_plan_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('phd_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('phd_acquisition_date', models.DateField()),
                ('phd_is_from_foreign_institute', models.BooleanField(default=False)),
                ('doatap_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('work_experience', models.IntegerField()),
                ('military_obligations_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cv_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('has_not_participated_in_past_program', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('paper_title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('journal_conf_title', models.CharField(max_length=255)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='app.application')),
            ],
        ),
    ]
