# Generated by Django 5.2.5 on 2025-08-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_title', models.CharField(blank=True, max_length=255, null=True)),
                ('phd_acquisition_date', models.DateField(blank=True, null=True)),
                ('phd_is_from_foreign_institute', models.BooleanField(blank=True, default=False, null=True)),
                ('scientific_field', models.CharField(blank=True, max_length=255, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('has_not_participated_in_past_program', models.BooleanField(blank=True, default=False, null=True)),
                ('cv_document', models.FileField(blank=True, max_length=255, null=True, upload_to='documents/')),
                ('phd_document', models.FileField(blank=True, max_length=255, null=True, upload_to='documents/')),
                ('doatap_document', models.FileField(blank=True, max_length=255, null=True, upload_to='documents/')),
                ('course_plan_document', models.FileField(blank=True, max_length=255, null=True, upload_to='documents/')),
                ('military_obligations_document', models.FileField(blank=True, max_length=255, null=True, upload_to='documents/')),
                ('course_plan_relevance_points', models.IntegerField(blank=True, default=0, null=True)),
                ('course_material_structure_points', models.IntegerField(blank=True, default=0, null=True)),
                ('thesis_relevance_points', models.IntegerField(blank=True, default=0, null=True)),
                ('paper_points', models.IntegerField(blank=True, default=0, null=True)),
                ('work_experience_points', models.IntegerField(blank=True, default=0, null=True)),
                ('not_past_program_points', models.IntegerField(blank=True, default=0, null=True)),
                ('total_points', models.IntegerField(blank=True, default=0, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('applicant', 'Applicant'), ('guest', 'Guest')], max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_title', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_conf_title', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('quartile', models.CharField(blank=True, max_length=10, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='app.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='app.user'),
        ),
    ]
