# Generated by Django 5.1.6 on 2025-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scientific_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
