# Generated by Django 5.2.5 on 2025-08-20 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.application')),
                ('scientific_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app.scientificfield')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('teaching_units', models.IntegerField(blank=True, null=True)),
                ('ects', models.FloatField(blank=True, null=True)),
                ('theory_hours', models.IntegerField(blank=True, null=True)),
                ('lab_hours', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('open_positions', models.IntegerField(blank=True, null=True)),
                ('scientific_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.scientificfield')),
            ],
        ),
    ]
