# Generated by Django 5.2.5 on 2025-08-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scientificfield_position_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.position'),
        ),
    ]
