# Generated by Django 5.2.5 on 2025-08-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_position_application_application_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='scientific_field',
        ),
        migrations.RemoveField(
            model_name='course',
            name='open_positions',
        ),
        migrations.AlterField(
            model_name='position',
            name='scientific_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='app.scientificfield'),
        ),
    ]
