# Generated by Django 5.2.5 on 2025-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_application_scientific_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificfield',
            name='school',
            field=models.CharField(default='jj', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
