# Generated by Django 5.1.6 on 2025-02-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_application_has_not_participated_in_past_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='quartile',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
