# Generated by Django 5.2.5 on 2026-04-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_scientificfield_school_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
