# Generated by Django 5.2.5 on 2026-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_position_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='active',
        ),
        migrations.AddField(
            model_name='position',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16),
        ),
    ]
