# Generated by Django 5.1.6 on 2025-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_paper_quartile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course_material_structure_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='course_plan_relevance_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='not_past_program_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='paper_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='thesis_relevance_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='total_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='work_experience_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
