# Generated by Django 5.2.5 on 2026-04-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_position_active_position_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='state',
        ),
    ]
