# Generated by Django 5.2.5 on 2026-04-06 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_position_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='position',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
