# Generated by Django 5.2.5 on 2026-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_certificate_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_public_employee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
