# Generated by Django 5.2.5 on 2026-04-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_application_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
