# Generated by Django 5.2.5 on 2026-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_address_application_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='public_employee_permission_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/'),
        ),
    ]
