# Generated by Django 5.2.5 on 2026-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_application_not_participated_declaration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='responsible_declaration_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/'),
        ),
    ]
