# Generated by Django 5.2.5 on 2026-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_application_responsible_declaration_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_eu_citizen_non_greek",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="eu_citizen_greek_language_certificate_document",
            field=models.FileField(blank=True, max_length=255, null=True, upload_to="documents/"),
        ),
    ]
