# Generated by Django 5.2.5 on 2026-04-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_employmentcertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='employment_certificate_document',
        ),
    ]
