# Generated by Django 5.2.5 on 2026-04-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_application_employment_certificate_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="BioSupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(max_length=255, upload_to="documents/")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bio_supporting_documents",
                        to="app.application",
                    ),
                ),
            ],
        ),
    ]