# Generated by Django 5.2.5 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_profile_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="closed_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
