# Generated by Django 6.0.5 on 2026-05-29 16:31

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_phd_profile_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='doc_type',
            field=models.CharField(choices=[('cv', 'CV'), ('phd', 'PhD'), ('doatap', 'DOATAP'), ('course_plan', 'Course Plan'), ('military', 'Military Obligations'), ('public_employee_permission', 'Public Employee Permission'), ('not_participated_declaration', 'Not Participated Declaration'), ('eu_citizen_greek_language_certificate', 'EU Citizen Greek Language Certificate'), ('responsible_declaration', 'Responsible Declaration'), ('bio_supporting', 'Bio Supporting'), ('employment_certificate', 'Employment Certificate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vaultdocument',
            name='doc_type',
            field=models.CharField(choices=[('cv', 'CV'), ('phd', 'PhD'), ('doatap', 'DOATAP'), ('course_plan', 'Course Plan'), ('military', 'Military Obligations'), ('public_employee_permission', 'Public Employee Permission'), ('not_participated_declaration', 'Not Participated Declaration'), ('eu_citizen_greek_language_certificate', 'EU Citizen Greek Language Certificate'), ('responsible_declaration', 'Responsible Declaration'), ('bio_supporting', 'Bio Supporting'), ('employment_certificate', 'Employment Certificate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vaultdocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=app.models.vault_document_upload_path),
        ),
        migrations.AlterField(
            model_name='vaultdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_documents', to='app.user'),
        ),
    ]
