# Generated by Django 6.0.5 on 2026-06-20 00:00

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model("app", "User")
    User.objects.all().update(verified=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_courseplan_weekly_schedule_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_users_verified, reverse_code=noop_reverse),
    ]
