# Generated by Django 6.0.5 on 2026-05-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_add_phdprofile_titles'),
        ('app', '0051_alter_applicationdocument_doc_type_and_more'),
    ]

    operations = [
    ]
