# Generated by Django 6.0.6 on 2026-06-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_user_verified'),
        ('app', '0062_user_must_change_password_and_history'),
    ]

    operations = [
    ]
