"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse
from dotenv import load_dotenv

load_dotenv()


def parse_env_bool(value, default=True):
    if value is None:
        return default
    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read media settings from .env
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, os.getenv("MEDIA_ROOT", "media"))
USE_S3_MEDIA = parse_env_bool(os.getenv("USE_S3_MEDIA", "false"), False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_env_bool(os.getenv("DJANGO_DEBUG", "true"), True)

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
ENV_ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").strip()
if ENV_ALLOWED_HOSTS:
    ALLOWED_HOSTS.extend(
        [h.strip() for h in ENV_ALLOWED_HOSTS.split(",") if h.strip()]
    )


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pgvector',
    'app',
    'rest_framework'
]
if USE_S3_MEDIA:
    INSTALLED_APPS.append('storages')

APPEND_SLASH = False

SECURE_SSL_REDIRECT = parse_env_bool(os.getenv("SECURE_SSL_REDIRECT", "false"), False)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = parse_env_bool(
    os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "false"),
    False,
)
SECURE_HSTS_PRELOAD = parse_env_bool(os.getenv("SECURE_HSTS_PRELOAD", "false"), False)
SESSION_COOKIE_SECURE = parse_env_bool(os.getenv("SESSION_COOKIE_SECURE", "false"), False)
CSRF_COOKIE_SECURE = parse_env_bool(os.getenv("CSRF_COOKIE_SECURE", "false"), False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'app.middleware.EmailVerificationRequiredMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL:
    parsed_database_url = urlparse(DATABASE_URL)
    parsed_query = parse_qs(parsed_database_url.query)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote(parsed_database_url.path.lstrip('/')),
            'USER': unquote(parsed_database_url.username or ''),
            'PASSWORD': unquote(parsed_database_url.password or ''),
            'HOST': parsed_database_url.hostname or '',
            'PORT': str(parsed_database_url.port or '5432'),
            'OPTIONS': {
                **({'sslmode': parsed_query['sslmode'][0]} if 'sslmode' in parsed_query else {}),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'prof_ranker_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if USE_S3_MEDIA:
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "").strip()
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "").strip()
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "").strip()
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "").strip()
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto").strip()
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "path"
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False

    s3_custom_domain = os.getenv("AWS_S3_CUSTOM_DOMAIN", "").strip()
    if s3_custom_domain:
        MEDIA_URL = f"https://{s3_custom_domain}/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CLIENT_URL = os.getenv("CLIENT_URL", "").strip()
CLIENT_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
if CLIENT_URL and CLIENT_URL not in CLIENT_ORIGINS:
    CLIENT_ORIGINS.append(CLIENT_URL)

CORS_ALLOWED_ORIGINS = CLIENT_ORIGINS
CSRF_TRUSTED_ORIGINS = CLIENT_ORIGINS

FRONTEND_BASE_URL = CLIENT_URL or "http://localhost:3000"
EMAIL_VERIFICATION_ENABLED = parse_env_bool(
    os.getenv("EMAIL_VERIFICATION_ENABLED", "true"),
    True,
)
EMAIL_VERIFICATION_SALT = os.getenv("EMAIL_VERIFICATION_SALT", "email-verification").strip()
EMAIL_VERIFICATION_TTL_SECONDS = int(os.getenv("EMAIL_VERIFICATION_TTL_SECONDS", "86400"))
EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS = int(
    os.getenv("EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS", "60")
)
EMAIL_VERIFICATION_DAILY_LIMIT = int(
    os.getenv("EMAIL_VERIFICATION_DAILY_LIMIT", "20")
)

RESEND_API_URL = os.getenv("RESEND_API_URL", "https://api.resend.com/emails").strip()
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "").strip()
RESEND_FROM_EMAIL = os.getenv(
    "RESEND_FROM_EMAIL",
    "ProfRanker <no-reply@mail.profrankerapp.com>",
).strip()
RESEND_EMAIL_TEMPLATE_PATH = os.getenv(
    "RESEND_EMAIL_TEMPLATE_PATH",
    os.path.join(BASE_DIR, "app", "templates", "email", "email_style.html"),
)
RESEND_EMAIL_LOGO_URL = os.getenv(
    "RESEND_EMAIL_LOGO_URL",
    "https://profrankerapp.com/ProfRanker-logo.png",
).strip()
RESEND_EMAIL_FOOTER = os.getenv(
    "RESEND_EMAIL_FOOTER",
    "Παρακαλώ μην απαντήσετε σε αυτό το email, καθώς αποστέλλεται αυτόματα και δεν παρακολουθείται.",
).strip()

CRON_SECRET = os.getenv("CRON_SECRET", "").strip()

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "cache"),
    }
}

